---
title: "Team R'hapsody"
sidebar: false 
---

This is our project webpage.

Please stay tuned to follow our project activities.

# Team Members

1.  Yusuf Karakulle

2.  Efe Kayra Torun

3.  Barış Aksu

4.  Firdevs Elif Batur

5.  Ramazan Ortasöz

# Project Topic

This project aims to deeply analyze one of the most significant macroeconomic indicators of
the Turkish economy, the Consumer Price Index (CPI), to better understand economic
dynamics. The CPI is a critical index used to measure price changes at the consumer level and
the overall inflation rate, providing insights into the general health of the economy. However,
examining the CPI in isolation may fall short of capturing the multidimensional factors
influencing it. Therefore, this project will comprehensively explore the relationship between
the CPI and other key economic indicators such as the Producer Price Index (PPI), exchange
rates, energy price index, housing price index, import price index, interest rates, consumer
confidence index, consumer expenditures, and credit card usage.

# Data Set

The data utilized in the project consists of the following indices and indicators:
• Producer Price Index (PPI)
• Exchange Rates
• Energy Price Index
• Housing Price Index
• Import Price Index
• Interest Rates
• Consumer Confidence Index
• Consumer Expenditures
• Credit Card Usage
The data for the analysis is sourced from reliable institutions such as the Turkish Statistical
Institute (TÜİK) and the Central Bank of the Republic of Turkey (TCMB). The dataset is
sufficiently large and up-to-date, enabling meaningful relationships to be established between
economic indicators.
The primary objective of the project is to identify the factors affecting the CPI, reveal how
these factors interact with the CPI, and provide a broader economic perspective based on the
findings. Statistical and data analysis methods will be employed to examine the correlations,
causality relationships, and temporal dynamics between the CPI and other indicators,
shedding light on which indicators have more pronounced impacts on the CPI. This process
will also help better understand critical dynamics unique to Turkey's economic structure, such
as the significant influence of exchange rates and energy prices on the CPI.
