<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Analysis – Rhapsody’s Project Lab</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Rhapsody’s Project Lab</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data.html"> 
<span class="menu-text">Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./analysis.html" aria-current="page"> 
<span class="menu-text">Analysis</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://twitter.com" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#regression-equation" id="toc-regression-equation" class="nav-link active" data-scroll-target="#regression-equation">1. <strong>Regression Equation</strong></a></li>
  <li><a href="#significance-of-coefficients" id="toc-significance-of-coefficients" class="nav-link" data-scroll-target="#significance-of-coefficients">2. <strong>Significance of Coefficients</strong></a></li>
  <li><a href="#model-fit" id="toc-model-fit" class="nav-link" data-scroll-target="#model-fit">3. <strong>Model Fit</strong></a></li>
  <li><a href="#overall-model-significance" id="toc-overall-model-significance" class="nav-link" data-scroll-target="#overall-model-significance">4. <strong>Overall Model Significance</strong></a></li>
  <li><a href="#residual-analysis" id="toc-residual-analysis" class="nav-link" data-scroll-target="#residual-analysis">5. <strong>Residual Analysis</strong></a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion:</a></li>
  <li><a href="#regression-equation-1" id="toc-regression-equation-1" class="nav-link" data-scroll-target="#regression-equation-1">1. <strong>Regression Equation</strong></a></li>
  <li><a href="#model-fit-1" id="toc-model-fit-1" class="nav-link" data-scroll-target="#model-fit-1">3. <strong>Model Fit</strong></a></li>
  <li><a href="#overall-model-significance-1" id="toc-overall-model-significance-1" class="nav-link" data-scroll-target="#overall-model-significance-1">4. <strong>Overall Model Significance</strong></a></li>
  <li><a href="#residual-analysis-1" id="toc-residual-analysis-1" class="nav-link" data-scroll-target="#residual-analysis-1">5. <strong>Residual Analysis</strong></a></li>
  <li><a href="#conclusion-1" id="toc-conclusion-1" class="nav-link" data-scroll-target="#conclusion-1">Conclusion:</a></li>
  <li><a href="#regression-equation-2" id="toc-regression-equation-2" class="nav-link" data-scroll-target="#regression-equation-2">1. <strong>Regression Equation</strong></a></li>
  <li><a href="#model-fit-2" id="toc-model-fit-2" class="nav-link" data-scroll-target="#model-fit-2">2. <strong>Model Fit</strong></a></li>
  <li><a href="#model-significance" id="toc-model-significance" class="nav-link" data-scroll-target="#model-significance">3. <strong>Model Significance</strong></a></li>
  <li><a href="#residual-analysis-2" id="toc-residual-analysis-2" class="nav-link" data-scroll-target="#residual-analysis-2">4. <strong>Residual Analysis</strong></a></li>
  <li><a href="#conclusion-2" id="toc-conclusion-2" class="nav-link" data-scroll-target="#conclusion-2">Conclusion:</a></li>
  <li><a href="#regression-equation-3" id="toc-regression-equation-3" class="nav-link" data-scroll-target="#regression-equation-3">1. <strong>Regression Equation</strong></a></li>
  <li><a href="#model-fit-3" id="toc-model-fit-3" class="nav-link" data-scroll-target="#model-fit-3">2. <strong>Model Fit</strong></a></li>
  <li><a href="#model-significance-1" id="toc-model-significance-1" class="nav-link" data-scroll-target="#model-significance-1">3. <strong>Model Significance</strong></a></li>
  <li><a href="#residual-analysis-3" id="toc-residual-analysis-3" class="nav-link" data-scroll-target="#residual-analysis-3">4. <strong>Residual Analysis</strong></a></li>
  <li><a href="#conclusion-3" id="toc-conclusion-3" class="nav-link" data-scroll-target="#conclusion-3">Conclusion:</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>KEY TAKEAWAYS</strong></p>
<ul>
<li><p>We calculated for correlation coefficients for all indicators and highest correlation coefficient is 0.88 between PPI and Housing Price Index.</p></li>
<li><p>We make a polynomial regression analysis for PPI and Credit Card Usage by taking a furter step analysis and it was a perfect fit for these two indicator.</p></li>
<li><p>We made a multiple regression analysis as our dependent variable PPI and our independent variables as Credit Card Usage,Housing Price Index and Consumer Confidence Index.And this model explains about <strong>80.12%</strong> of the variability in <strong>PPI</strong>, which is strong.</p></li>
</ul>
<p><strong>1-Producer Price Index vs Consumer Price Index</strong></p>
<p>In this study, the relationship between the Producer Price Index (PPI) and the Consumer Price Index (CPI) has been analyzed. While PPI measures changes in the prices of goods and services at the producer level, CPI reflects changes in the prices paid by consumers. The interaction between these indices is crucial for understanding price formation processes, as changes in production costs (PPI) can often translate into consumer prices (CPI). This analysis examines how changes in PPI affect CPI and evaluates the interaction between these two economic indicators. Using historical data and various statistical methods, the direction and magnitude of this relationship have been revealed.</p>
<p>Based on this analysis we will choose PPI or CPI as our baseline to compare it’s effects on other economic indicators.</p>
<p>First let’s look the table we will use for analysis.We used annual percentage changes of the variables as index values.</p>
<p>First let’s look the table we will use for analysis.We used annual percentage changes of the variables as index values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(table_ppi_cpi,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   Tarih        PPI   CPI
   &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt;
 1 2019-01-01 32.9  20.4 
 2 2019-02-01 29.6  19.7 
 3 2019-03-01 29.6  19.7 
 4 2019-04-01 30.1  19.5 
 5 2019-05-01 28.7  18.7 
 6 2019-06-01 25.0  15.7 
 7 2019-07-01 21.7  16.6 
 8 2019-08-01 13.4  15.0 
 9 2019-09-01  2.45  9.26
10 2019-10-01  1.7   8.55</code></pre>
</div>
</div>
<p>We will plot a line graph where we will show both index as a variable over time.This will help us to visualize their relation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>graph_line1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(table_ppi_cpi, <span class="fu">aes</span>(<span class="at">x =</span> Tarih)) <span class="sc">+</span>      </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> PPI, <span class="at">color =</span> <span class="st">"PP Index(%)"</span> )) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> CPI, <span class="at">color =</span> <span class="st">"Cp Index(%)"</span>)) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"PP Index(%)"</span> <span class="ot">=</span> <span class="st">"black"</span>, <span class="st">"Cp Index(%)"</span> <span class="ot">=</span> <span class="st">"blue"</span>)) <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"PPI&amp;CPI Graph"</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Tarih"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Variable"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Variables"</span>) <span class="sc">+</span> </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span><span class="fu">theme_economist</span>()</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>graph_line1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As you can see in the graph above,it seems both indexes have a similar behaviour over time.By just looking at this graph,we may think there is a strong relation between them.They track each others movement on the graph.But just visuality may not be enough therefore we will do a correlation test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>cor_ppi_cpi <span class="ot">&lt;-</span> <span class="fu">cor</span>(table_ppi_cpi<span class="sc">$</span>PPI, table_ppi_cpi<span class="sc">$</span>CPI)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_ppi_cpi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7959363</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cortest_ppi_cpi <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(table_ppi_cpi<span class="sc">$</span>PPI, table_ppi_cpi<span class="sc">$</span>CPI)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cortest_ppi_cpi<span class="sc">$</span>p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.087791e-16</code></pre>
</div>
</div>
<p>This correlation value supports visual data and says there is really strong relation between them.Also, p-value(1.087791e-16) is very low.Usually,results are considered significant if they are less than 0.5.In this case, the probability of the course of the situation arising by chance is extremely low.But what happens if there is some lag between interaction.Let’s do some lagged correlation tests.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>data_ppi_cpi<span class="ot">&lt;-</span> table_ppi_cpi <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PPI_lag1 =</span> <span class="fu">lag</span>(PPI, <span class="dv">1</span>),</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">PPI_lag2 =</span> <span class="fu">lag</span>(PPI, <span class="dv">2</span>),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">PPI_lag3 =</span> <span class="fu">lag</span>(PPI, <span class="dv">3</span>),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">PPI_lag4 =</span> <span class="fu">lag</span>(PPI, <span class="dv">4</span>),<span class="at">PPI_lag5 =</span> <span class="fu">lag</span>(PPI, <span class="dv">5</span>))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>cor_lag1_ppi_cpi <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_ppi_cpi<span class="sc">$</span>PPI_lag1, data_ppi_cpi<span class="sc">$</span>CPI, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>cor_lag2_ppi_cpi <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_ppi_cpi<span class="sc">$</span>PPI_lag2, data_ppi_cpi<span class="sc">$</span>CPI, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>cor_lag3_ppi_cpi <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_ppi_cpi<span class="sc">$</span>PPI_lag3, data_ppi_cpi<span class="sc">$</span>CPI, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>cor_lag4_ppi_cpi <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_ppi_cpi<span class="sc">$</span>PPI_lag4, data_ppi_cpi<span class="sc">$</span>CPI, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_lag1_ppi_cpi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8098936</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_lag2_ppi_cpi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7947913</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_lag3_ppi_cpi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7669985</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_lag4_ppi_cpi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.732202</code></pre>
</div>
</div>
<p>Highest correlation is 0.809 with a 1 unit time lag.More than 1 unit time lag,correlation values is decreasing and they are less than original correlation value.There is not an obvious increase on values with lag.But still it’s proves there is a strong relation between two index.But which index affects the other?Which index should we use as a independent variable to analyse other economic indicators’s behaviours?We should Grenger casuality test to decide.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grangertest</span>(PPI <span class="sc">~</span> CPI, <span class="at">order =</span> <span class="dv">2</span>, <span class="at">data =</span> table_ppi_cpi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Granger causality test

Model 1: PPI ~ Lags(PPI, 1:2) + Lags(CPI, 1:2)
Model 2: PPI ~ Lags(PPI, 1:2)
  Res.Df Df      F Pr(&gt;F)
1     64                 
2     66 -2 2.3675 0.1019</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grangertest</span>(CPI <span class="sc">~</span> PPI, <span class="at">order =</span> <span class="dv">2</span>, <span class="at">data =</span> table_ppi_cpi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Granger causality test

Model 1: CPI ~ Lags(CPI, 1:2) + Lags(PPI, 1:2)
Model 2: CPI ~ Lags(CPI, 1:2)
  Res.Df Df      F    Pr(&gt;F)    
1     64                        
2     66 -2 11.208 6.712e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>First Granger test examines if CPI affects PPI values and it has a p-value as 0.1019 which is too high.That means CPI values does not have a effect on PPI values. On the other hand,second Granger test examinse if PPI affects CPI values and it has a p-value as 6.712e-05 which is very low.Generally p-values less than 0.05 considered statistically meaningful.Thus,we can say PPI values does affect CPI values. Finally we can say PPI can be independent variable for our further analysis.That’s why we choose PPI as our inflation rate. Before continue on further analysis we will do a regression analysis between PPI and CPI to better understanding of their relation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>reg_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(CPI <span class="sc">~</span> PPI, <span class="at">data =</span> data_ppi_cpi)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = CPI ~ PPI, data = data_ppi_cpi)

Residuals:
    Min      1Q  Median      3Q     Max 
-19.811 -10.354  -6.141   5.421  32.803 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 13.99397    2.91415   4.802  8.8e-06 ***
PPI          0.49669    0.04548  10.921  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 15.49 on 69 degrees of freedom
Multiple R-squared:  0.6335,    Adjusted R-squared:  0.6282 
F-statistic: 119.3 on 1 and 69 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Let’s analyse this result.</p>
<p><strong>Intercept:13.99</strong></p>
<p>This represents the predicted value of CPI when PPI (index) is zero.Practically, it indicates the starting point.</p>
<p><strong>PPI Coefficient (index):0.49669</strong></p>
<p>This coefficient shows that a one-unit increase in PPI leads to an average increase of 0.497 units in CPI. The positive sign indicates that an increase in PPI results in an increase in CPI.</p>
<p><strong>P-values (for coefficients):</strong></p>
<p><strong>Intercept:p=8.8𝑒-0.6 PPI coefficient=p&lt;2𝑒-16</strong></p>
<p>Since the p-values for both coefficients are less than 0.05, they are statistically significant. This supports the conclusion that the independent variable (PPI) has a significant effect on the dependent variable (CPI).</p>
<p><strong>Multiple R-squared:0.6335</strong></p>
<p>This value indicates that the model explains 63.35% of the total variation in the CPI variable. This suggests a strong relationship, although 36.65% of the variation remains unexplained. The model has reasonable explanatory power.</p>
<p><strong>F-Statistic:119.3, p&lt; 2.2𝑒- 16</strong></p>
<p>This test evaluates the overall significance of the model. It shows that PPI is a significant variable for predicting CPI. The very small p-value (&lt; 0.05) confirms that the model as a whole is statistically significant.</p>
<p><strong>Regression equation:</strong></p>
<p><strong>CPI = 13.99 + 0.49669.PPI</strong></p>
<p>And there is graph with regression line.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>data_ppi_cpi<span class="sc">$</span>Tarih <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="fu">paste0</span>(<span class="st">"01-"</span>, data_ppi_cpi<span class="sc">$</span>Tarih), <span class="at">format =</span> <span class="st">"%d-%m-%Y"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>reg_graph<span class="ot">&lt;-</span><span class="fu">ggplot</span>(data_ppi_cpi, <span class="fu">aes</span>(<span class="at">x =</span> PPI, <span class="at">y =</span> CPI)) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Regression Analysis: PPI vs CPI"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Producer Price Index (PPI)"</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Consumer Price Index (CPI)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$x
[1] "Producer Price Index (PPI)"

$y
[1] "Consumer Price Index (CPI)"

$title
[1] "Regression Analysis: PPI vs CPI"

attr(,"class")
[1] "labels"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>reg_graph</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>2-Producer Price Index vs Credit Card Usage</strong></p>
<p>In this study, the relationship between the Producer Price Index (PPI) and credit card usage has been analyzed. PPI measures changes in the prices of goods and services at the producer level, while credit card usage is an important indicator reflecting consumer spending habits and economic activity. The interaction between these two variables is critical for understanding the impact of economic fluctuations and price changes on consumer behavior. Using historical data, the study examines how changes in PPI affect credit card usage and evaluates the direction and magnitude of this relationship through various statistical methods.</p>
<p>Data we will use is again annual percentage changes for both variables and it accounts last 6 years since 2019.</p>
<p>First let’s take a look our data frame!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(table_ppi_ccu,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   Tarih        PPI  usage
   &lt;date&gt;     &lt;dbl&gt;  &lt;dbl&gt;
 1 2019-01-01 32.9   13.2 
 2 2019-02-01 29.6   13.5 
 3 2019-03-01 29.6   15.9 
 4 2019-04-01 30.1   10.1 
 5 2019-05-01 28.7   40.9 
 6 2019-06-01 25.0  -10.3 
 7 2019-07-01 21.7   13.2 
 8 2019-08-01 13.4   12.3 
 9 2019-09-01  2.45   6.35
10 2019-10-01  1.7    8.52</code></pre>
</div>
</div>
<p><em>PPI=PRODUCER PRICE INDEX</em></p>
<p><em>USAGE=CREDİT CART USAGE AMOUNT</em></p>
<p>We will plot a line graph where we will show both index as a variable over time.This will help us to visualize their relation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>ggp2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(table_ppi_ccu, <span class="fu">aes</span>(<span class="at">x =</span> Tarih)) <span class="sc">+</span>      </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> PPI, <span class="at">color =</span> <span class="st">"PP Index"</span>)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> usage, <span class="at">color =</span> <span class="st">"CC Usage"</span>)) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"PP Index"</span> <span class="ot">=</span> <span class="st">"black"</span>, <span class="st">"CC Usage"</span> <span class="ot">=</span> <span class="st">"blue"</span>)) <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"PPI&amp;CCU Graph"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Variables(%)"</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Variables"</span>) <span class="sc">+</span> </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span><span class="fu">theme_economist</span>()</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>ggp2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can make a legitimate guess about their relation with this visualized data.But we need analytical results to interpret the results.Therefore, we will do a correlation test between them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>cor_ppi_ccu <span class="ot">&lt;-</span> <span class="fu">cor</span>(table_ppi_ccu<span class="sc">$</span>PPI, table_ppi_ccu<span class="sc">$</span>usage)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>cortest_ppi_ccu <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(table_ppi_ccu<span class="sc">$</span>PPI, table_ppi_ccu<span class="sc">$</span>usage)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_ppi_ccu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.60305</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cortest_ppi_ccu<span class="sc">$</span>p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.615285e-08</code></pre>
</div>
</div>
<p>Correlation value for PPI and CCU is 0.603 which is pretty high.This means there is a relaively strong relation between them.Also p-value is less than 0.05 which means it is statistically meaningful.We also will do a correlation test with time lag to go deeper.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>data_ppi_ccu <span class="ot">&lt;-</span> table_ppi_ccu <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PPI_lag1 =</span> <span class="fu">lag</span>(PPI, <span class="dv">1</span>),</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">PPI_lag2 =</span> <span class="fu">lag</span>(PPI, <span class="dv">2</span>),</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">PPI_lag3 =</span> <span class="fu">lag</span>(PPI, <span class="dv">3</span>),</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">PPI_lag4=</span><span class="fu">lag</span>(PPI,<span class="dv">4</span>),</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">PPI_lag5=</span><span class="fu">lag</span>(PPI,<span class="dv">5</span>))</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>cor_lag1_ppi_ccu <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_ppi_ccu<span class="sc">$</span>PPI_lag1, data_ppi_ccu<span class="sc">$</span>usage, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>cor_lag2_ppi_ccu <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_ppi_ccu<span class="sc">$</span>PPI_lag2, data_ppi_ccu<span class="sc">$</span>usage, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>cor_lag3_ppi_ccu <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_ppi_ccu<span class="sc">$</span>PPI_lag3, data_ppi_ccu<span class="sc">$</span>usage, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>cor_lag4_ppi_ccu <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_ppi_ccu<span class="sc">$</span>PPI_lag4, data_ppi_ccu<span class="sc">$</span>usage, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>cor_lag5_ppi_ccu <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_ppi_ccu<span class="sc">$</span>PPI_lag5, data_ppi_ccu<span class="sc">$</span>usage, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_lag1_ppi_ccu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6165495</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_lag2_ppi_ccu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6422825</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_lag3_ppi_ccu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6536861</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_lag4_ppi_ccu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6713074</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_lag5_ppi_ccu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6726063</code></pre>
</div>
</div>
<p>As the lag time increases, the correlation value increases. After the 4th and 5th delay, the rate of increase slows down.So we can say PPI values causes CCU Therefore, we can say that PPI has a delayed effect on credit card usage which is higher than correlation value without time lag.</p>
<p><strong>3-PRODUCER PRICE INDEX VS INTEREST RATE</strong></p>
<p>In this study, the relationship between the Producer Price Index (PPI) and interest rates has been analyzed. While PPI measures changes in the prices of goods and services at the producer level, interest rates are a critical macroeconomic indicator influencing economic growth, consumption, and investment decisions. The interaction between these two variables is significant for understanding inflation dynamics and supporting economic policy decisions. Using historical data, the study evaluates the impact of changes in PPI on interest rates and examines the direction and magnitude of this relationship through various statistical methods.First let’s take a look at our data table:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_yusuf0,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   DATE         PPI    IR
   &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt;
 1 2019-01-01 32.9   30.5
 2 2019-02-01 29.6   26.2
 3 2019-03-01 29.6   22.8
 4 2019-04-01 30.1   24.3
 5 2019-05-01 28.7   27.8
 6 2019-06-01 25.0   28.6
 7 2019-07-01 21.7   26.9
 8 2019-08-01 13.4   21.2
 9 2019-09-01  2.45  18.2
10 2019-10-01  1.7   17.2</code></pre>
</div>
</div>
<p>Now we will sketch a graph line for visualization purposes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>data_yusuf, <span class="fu">aes</span>(<span class="at">x=</span>DATE)) <span class="sc">+</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>PPI, <span class="at">color=</span><span class="st">"PPI"</span>), <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>IR, <span class="at">color=</span><span class="st">"Interest Rate (IR)"</span>), <span class="at">size=</span><span class="dv">1</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"PPI vs Interest Rate Over Time"</span>, <span class="at">x=</span><span class="st">"Date"</span>, <span class="at">y=</span><span class="st">"Values"</span>, <span class="at">color=</span><span class="st">"Legend"</span>) <span class="sc">+</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_economist</span>() <span class="sc">+</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_economist</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Because we need analytical data we will implement a correlation test for this two economic indicators.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>cor_interest <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_yusuf<span class="sc">$</span>PPI, data_yusuf<span class="sc">$</span>IR)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_interest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1198634</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>cortest_interest <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(data_yusuf<span class="sc">$</span>PPI, data_yusuf<span class="sc">$</span>IR)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cortest_interest<span class="sc">$</span>p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3194176</code></pre>
</div>
</div>
<p>Correlation value is 0.119 which means these two indicators does not have a strong relation.Also p-value is more than 0.05 and this indicates this correlation value is NOT significantly meaningfull.To conclude,we can say we did not find a clue about relation between PPI and Interest Rate indicators.</p>
<p><strong>4-PRODUCER PRICE INDEX VS CONSUMER CONFIDENCE INDEX</strong></p>
<p>This study analyzes the relationship between the Producer Price Index (PPI) and the Consumer Confidence Index (CCI). While PPI measures changes in the prices of goods and services at the producer level, the Consumer Confidence Index reflects the sentiment and expectations of consumers regarding the economy. Understanding the interaction between these two indicators is crucial for assessing the impact of price changes on consumer perceptions and behavior. Using historical data, the study examines how changes in PPI influence consumer confidence and evaluates the direction and magnitude of this relationship through various statistical methods.</p>
<p>First let’s take a look at our data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_yusuf1,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   DATE         PPI   CCI
   &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt;
 1 2019-01-01 32.9   127.
 2 2019-02-01 29.6   131.
 3 2019-03-01 29.6   140.
 4 2019-04-01 30.1   139.
 5 2019-05-01 28.7   143.
 6 2019-06-01 25.0   153.
 7 2019-07-01 21.7   148.
 8 2019-08-01 13.4   130.
 9 2019-09-01  2.45  139.
10 2019-10-01  1.7   142.</code></pre>
</div>
</div>
<p>And again as we have done all above we will sketch a line graph:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>graph_yusuf1<span class="ot">&lt;-</span><span class="fu">ggplot</span>(<span class="at">data=</span>data_yusuf, <span class="fu">aes</span>(<span class="at">x=</span>DATE)) <span class="sc">+</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>PPI, <span class="at">color=</span><span class="st">"PPI"</span>), <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>CCI, <span class="at">color=</span><span class="st">"Consumer Confidence Index (CCI)"</span>), <span class="at">size=</span><span class="dv">1</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"PPI vs Consumer Confidence Index Over Time"</span>, <span class="at">x=</span><span class="st">"Date"</span>, <span class="at">y=</span><span class="st">"Values"</span>, <span class="at">color=</span><span class="st">"Legend"</span>) <span class="sc">+</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_economist</span>() <span class="sc">+</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_economist</span>()</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>graph_yusuf1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can not clearly see their relation by just looking at it therefore we will conduct a correlation test again.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>cor_confidence <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_yusuf<span class="sc">$</span>PPI, data_yusuf<span class="sc">$</span>CCI)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_confidence)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4221268</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>cortest_confidence <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(data_yusuf<span class="sc">$</span>PPI, data_yusuf<span class="sc">$</span>CCI)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cortest_confidence<span class="sc">$</span>p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0002456725</code></pre>
</div>
</div>
<p>0.422 is relatively low to say these indicators has a notable relation but p-value is low enough to be statisticaly meaningful.So we can easily say we can confirm that there is a relation bewteen PPI and CCI and this relation is not strong.</p>
<p><strong>5-PRODUCER PRICE INDEX VS HOUSUNG PRICE INDEX</strong></p>
<p>This study examines the relationship between the Producer Price Index (PPI) and the Housing Price Index (HPI). While PPI tracks changes in the prices of goods and services at the producer level, HPI reflects fluctuations in residential property prices. Understanding the interaction between these two indices is essential for analyzing how changes in production costs influence the housing market. Using historical data, the study investigates the impact of PPI on housing prices and evaluates the direction and strength of this relationship through various statistical methods.</p>
<p>Let’s take a look at our table!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ppi_housing,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Tarih   PPI Housing_Percentage_Change
1  2019-01-01 32.93                  3.362152
2  2019-02-01 29.59                  3.625954
3  2019-03-01 29.64                  3.122044
4  2019-04-01 30.12                  2.054155
5  2019-05-01 28.71                  1.473297
6  2019-06-01 25.04                  1.741522
7  2019-07-01 21.66                  2.836231
8  2019-08-01 13.45                  5.243790
9  2019-09-01  2.45                  6.864564
10 2019-10-01  1.70                  6.912442</code></pre>
</div>
</div>
<p>Now we will plot a graph line:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>ppi_housing_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ppi_housing, <span class="fu">aes</span>(<span class="at">x =</span> Tarih)) <span class="sc">+</span>      </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> PPI, <span class="at">color =</span> <span class="st">"PPI"</span>)) <span class="sc">+</span>  </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Housing_Percentage_Change, <span class="at">color =</span> <span class="st">"Housing Change"</span>)) <span class="sc">+</span>  </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"PPI"</span> <span class="ot">=</span> <span class="st">"red"</span>, <span class="st">"Housing Change"</span> <span class="ot">=</span> <span class="st">"blue"</span>)) <span class="sc">+</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"PPI &amp; Housing Change Graph"</span>,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Tarih"</span>,</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Variable"</span>,</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Variables"</span>) <span class="sc">+</span> </span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_economist</span>()</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ppi_housing_graph)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see in the graph that this tho index values are almost stick to each other.Now let’s do a correlation test and see if we can verify that.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>correlation_house <span class="ot">&lt;-</span> <span class="fu">cor</span>(ppi_housing<span class="sc">$</span>PPI, ppi_housing<span class="sc">$</span>Housing_Percentage_Change, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Korelasyon Katsayısı: "</span>, correlation_house))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Korelasyon Katsayısı:  0.888596687452896"</code></pre>
</div>
</div>
<p>According to this correlation value,these two indicators has a ver powerful relation which verify our visual observatoin.And p-value is too low which means this relation is statistically meaningful.</p>
<p><strong>6-PRODUCER PRICE INDEX and ENERGY PRICE INDEX</strong></p>
<p>This study explores the relationship between the Producer Price Index (PPI) and Brent Oil prices. PPI measures changes in the prices of goods and services at the producer level, while Brent Crude Oil serves as a benchmark for global oil prices, influencing production costs across various industries. The interaction between these two indicators is critical for understanding the impact of energy price fluctuations on broader economic price dynamics. Using historical data, the study investigates how changes in Brent Crude Oil prices affect PPI and evaluates the direction and magnitude of this relationship through various statistical methods.</p>
<p>Let’s take a look our data frame!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ppi_petrol,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Tarih   PPI TP_BrentPetrol
1  2019-01-01 32.93      -7.848923
2  2019-02-01 29.59      -1.588983
3  2019-03-01 29.64      -1.579252
4  2019-04-01 30.12      -4.913066
5  2019-05-01 28.71     -12.648790
6  2019-06-01 25.04     -12.809917
7  2019-07-01 21.66     -13.605717
8  2019-08-01 13.45     -20.665454
9  2019-09-01  2.45     -26.269342
10 2019-10-01  1.70     -20.764297</code></pre>
</div>
</div>
<p>Now let’s sketch a graph line and then calculate correlation value to see these two indicator’s relation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>ppi_petrol_graph <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ppi_petrol, <span class="fu">aes</span>(<span class="at">x =</span> Tarih)) <span class="sc">+</span>      </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> PPI, <span class="at">color =</span> <span class="st">"PPI"</span>)) <span class="sc">+</span>  </span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> TP_BrentPetrol, <span class="at">color =</span> <span class="st">"Petrol Change"</span>)) <span class="sc">+</span>  </span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"PPI"</span> <span class="ot">=</span> <span class="st">"red"</span>, <span class="st">"Petrol Change"</span> <span class="ot">=</span> <span class="st">"blue"</span>)) <span class="sc">+</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"PPI &amp; Petrol Change Graph"</span>,</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Tarih"</span>,</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Variable"</span>,</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Variables"</span>) <span class="sc">+</span> </span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_economist</span>()</span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ppi_petrol_graph)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 7 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Correlation for PPI and Brent Oil prices:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>correlation_petrol <span class="ot">&lt;-</span> <span class="fu">cor</span>(ppi_petrol<span class="sc">$</span>PPI, ppi_petrol<span class="sc">$</span>TP_BrentPetrol, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Korelasyon Katsayısı: "</span>, correlation_petrol))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Korelasyon Katsayısı:  0.247511777625547"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>cortest_petrol<span class="ot">&lt;-</span><span class="fu">cor.test</span>(ppi_petrol<span class="sc">$</span>PPI, ppi_petrol<span class="sc">$</span>TP_BrentPetrol)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"P-Value: "</span>,cortest_petrol<span class="sc">$</span>p.value))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "P-Value:  0.0468302492457841"</code></pre>
</div>
</div>
<p>Correlation valu for PPI and Brent Oil prices is 0.603 which is moderatly high.P-value is 0.03 means this correlation test is statistically meaningful.We can say that there is a relation between these two economic indicators.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dataefe, <span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   Date       `PPI (%)`   USD `Import Unit Value Index (TL)`
   &lt;date&gt;         &lt;dbl&gt; &lt;dbl&gt;                          &lt;dbl&gt;
 1 2019-01-01    0.329   5.37                           207.
 2 2019-02-01    0.296   5.26                           201.
 3 2019-03-01    0.296   5.44                           210.
 4 2019-04-01    0.301   5.74                           220.
 5 2019-05-01    0.287   6.05                           228.
 6 2019-06-01    0.250   5.81                           219.
 7 2019-07-01    0.217   5.67                           213.
 8 2019-08-01    0.134   5.62                           207.
 9 2019-09-01    0.0245  5.71                           209.
10 2019-10-01    0.017   5.78                           212.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>scale_usd <span class="ot">&lt;-</span> <span class="fu">max</span>(dataefe<span class="sc">$</span><span class="st">`</span><span class="at">PPI (%)</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">max</span>(dataefe<span class="sc">$</span>USD, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>scale_import <span class="ot">&lt;-</span> <span class="fu">max</span>(dataefe<span class="sc">$</span><span class="st">`</span><span class="at">PPI (%)</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">max</span>(dataefe<span class="sc">$</span><span class="st">`</span><span class="at">Import Unit Value Index (TL)</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>graph_usd <span class="ot">&lt;-</span> dataefe <span class="sc">|&gt;</span> </span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Date)) <span class="sc">+</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="st">`</span><span class="at">PPI (%)</span><span class="st">`</span>, <span class="at">color =</span> <span class="st">"PPI (%)"</span>)) <span class="sc">+</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> USD <span class="sc">*</span> scale_usd, <span class="at">color =</span> <span class="st">"Exchange Rate (USD)"</span>)) <span class="sc">+</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"PPI (%)"</span>,</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sec.axis =</span> <span class="fu">sec_axis</span>(<span class="sc">~</span> . <span class="sc">/</span> scale_usd, <span class="at">name =</span> <span class="st">"Exchange Rate (USD)"</span>)</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"PPI (%)"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"Exchange Rate (USD)"</span> <span class="ot">=</span> <span class="st">"red"</span>)) <span class="sc">+</span></span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"PPI (%) vs Exchange Rate (USD) Over Time"</span>,</span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"PPI (%)"</span>,</span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Variables"</span>) <span class="sc">+</span></span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_economist</span>()</span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a>graph_usd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>graph_import <span class="ot">&lt;-</span> dataefe <span class="sc">|&gt;</span> </span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Date)) <span class="sc">+</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="st">`</span><span class="at">PPI (%)</span><span class="st">`</span>, <span class="at">color =</span> <span class="st">"PPI (%)"</span>)) <span class="sc">+</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="st">`</span><span class="at">Import Unit Value Index (TL)</span><span class="st">`</span> <span class="sc">*</span> scale_import, <span class="at">color =</span> <span class="st">"Import Price Index (TL)"</span>)) <span class="sc">+</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"PPI (%)"</span>,</span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sec.axis =</span> <span class="fu">sec_axis</span>(<span class="sc">~</span> . <span class="sc">/</span> scale_import, <span class="at">name =</span> <span class="st">"Import Price Index (TL)"</span>)</span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"PPI (%)"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"Import Price Index (TL)"</span> <span class="ot">=</span> <span class="st">"orange"</span>)) <span class="sc">+</span></span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"PPI (%) vs Import Price Index (TL) Over Time"</span>,</span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"PPI (%)"</span>,</span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Variables"</span>) <span class="sc">+</span></span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb75-15"><a href="#cb75-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_economist</span>()</span>
<span id="cb75-16"><a href="#cb75-16" aria-hidden="true" tabindex="-1"></a>graph_import</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>cor_ppi_usd <span class="ot">&lt;-</span> dataefe <span class="sc">%&gt;%</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">correlation =</span> <span class="fu">cor</span>(<span class="st">`</span><span class="at">PPI (%)</span><span class="st">`</span>, USD, <span class="at">use =</span> <span class="st">"complete.obs"</span>, <span class="at">method =</span> <span class="st">"pearson"</span>))</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>cor_ppi_import <span class="ot">&lt;-</span> dataefe <span class="sc">%&gt;%</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">correlation =</span> <span class="fu">cor</span>(<span class="st">`</span><span class="at">PPI (%)</span><span class="st">`</span>, <span class="st">`</span><span class="at">Import Unit Value Index (TL)</span><span class="st">`</span>, <span class="at">use =</span> <span class="st">"complete.obs"</span>, <span class="at">method =</span> <span class="st">"pearson"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>cor_ppi_usd<span class="sc">$</span>correlation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3080418</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>cor_ppi_import<span class="sc">$</span>correlation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4149023</code></pre>
</div>
</div>
<p><strong>INDICATORS WHICH HAS MOST STRONG RELATİON WITH PPI</strong></p>
<p><strong>Correlation Coefficient:</strong></p>
<p>• Exchange Rates- Producer Price Index (PPI)= 0.30804</p>
<p>• Energy Price Index- Producer Price Index (PPI)= 0.25689</p>
<p>• Housing Price Index- Producer Price Index (PPI)= 0.88859</p>
<p>• Import Price Index- Producer Price Index (PPI)= 0.41490</p>
<p>• Interest Rates- Producer Price Index (PPI)= 0.11986</p>
<p>• Consumer Confidence Index- Producer Price Index (PPI)= 0.42212</p>
<p>• Consumer Price Index- Producer Price Index (PPI)= 0.7959363</p>
<p>• Credit Card Usage- Producer Price Index (PPI)= 0.60305</p>
<p>We can choose the four most important and influential variables from the dataset we are using, then run a regression analysis to see which factors have the biggest effects on the PPI. We may learn more about the characteristics of the models we should concentrate on and how to enhance them to increase their efficacy or predictive power after performing this regression study. Our best 4 atrribute:</p>
<ul>
<li><p>Consumer Price Index- Producer Price Index (PPI)= 0.7959363</p></li>
<li><p>Housing Price Index- Producer Price Index (PPI)= 0.888596687452896</p></li>
<li><p>Consumer Confidence Index- Producer Price Index (PPI)= 0.42212</p></li>
<li><p>Credit Card Usage- Producer Price Index (PPI)= 0.60305</p></li>
</ul>
<p><strong>PIE CHART FOR CORRELATION VALUES BETWEEN PPI AND FOUR INDICATORS</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>labels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Consumer Price Index"</span>, <span class="st">"Housing Price Index"</span>, </span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Interest Rates"</span>, <span class="st">"Consumer Confidence Index"</span>)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>correlations <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.7959363</span>, <span class="fl">0.88859</span>, <span class="fl">0.42212</span>,<span class="fl">0.60305</span>)</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>total <span class="ot">&lt;-</span> <span class="fu">sum</span>(correlations)</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>percentages <span class="ot">&lt;-</span> (correlations <span class="sc">/</span> total) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>))  </span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a><span class="fu">pie</span>(</span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>  percentages, </span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">paste0</span>(labels, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">sprintf</span>(<span class="st">"%.1f%%"</span>, percentages)), </span>
<span id="cb81-12"><a href="#cb81-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> (<span class="st">"Etki Yuzdeleri: PPI ile Korelasyon"</span>),</span>
<span id="cb81-13"><a href="#cb81-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="fu">length</span>(labels)),</span>
<span id="cb81-14"><a href="#cb81-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex =</span> <span class="fl">0.8</span>  </span>
<span id="cb81-15"><a href="#cb81-15" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>REGRESSION ANALYSIS</strong></p>
<p><strong>PPI and CREDIT CARD USAGE</strong></p>
<p>On our previous analysis we have seen that credit card usage and PPI has a relatively strong relation.An increasing on PPI cause an increase on CCU usually.We will take a further step and make a regression analysis for them.Our purpose is have a better understanding about this two indicators relation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>regmodel_ppiccu <span class="ot">&lt;-</span> <span class="fu">lm</span>(usage <span class="sc">~</span> PPI, <span class="at">data =</span> table1)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regmodel_ppiccu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = usage ~ PPI, data = table1)

Residuals:
   Min     1Q Median     3Q    Max 
-74.31 -29.70 -13.62  24.07 102.06 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  31.3077     8.0262   3.901  0.00022 ***
PPI           0.7866     0.1253   6.280 2.62e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 42.66 on 69 degrees of freedom
Multiple R-squared:  0.3637,    Adjusted R-squared:  0.3544 
F-statistic: 39.43 on 1 and 69 DF,  p-value: 2.615e-08</code></pre>
</div>
</div>
<p>The regression analysis output provides insights into the relationship between <strong>CCU</strong> (dependent variable) and <strong>PPI</strong> (independent variable). Here’s the detailed interpretation:</p>
<section id="regression-equation" class="level3">
<h3 class="anchored" data-anchor-id="regression-equation">1. <strong>Regression Equation</strong></h3>
<p>From the coefficients:</p>
<ul>
<li><p><strong>Intercept:</strong> 31.3077</p></li>
<li><p><strong>PPI Coefficient:</strong> 0.78660</p></li>
</ul>
<p>The regression equation is:</p>
<p><strong>CCU=31.31+0.7866⋅PPI</strong></p>
<p>This indicates:</p>
<ul>
<li><p>For every 1-unit increase in <strong>PPI</strong>, the predicted <strong>CCU</strong> increases by approximately <strong>0.787 units</strong>.</p></li>
<li><p>When <strong>PPI</strong> is zero, the predicted <strong>usage</strong> is approximately <strong>31.31</strong>.</p></li>
</ul>
</section>
<section id="significance-of-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="significance-of-coefficients">2. <strong>Significance of Coefficients</strong></h3>
<ul>
<li><p>The <strong>p-value</strong> for the intercept is <strong>0.00022</strong>, and for the PPI coefficient, it is <strong>2.62e-08</strong>. Both are much smaller than <strong>0.05</strong>, indicating that the coefficients are statistically significant.</p></li>
<li><p>This means that <strong>PPI</strong> has a meaningful effect on <strong>CCU</strong></p></li>
</ul>
</section>
<section id="model-fit" class="level3">
<h3 class="anchored" data-anchor-id="model-fit">3. <strong>Model Fit</strong></h3>
<ul>
<li><p><strong>Multiple R-squared:</strong> 0.3637</p>
<ul>
<li><p>This value suggests that the model explains <strong>36.37% of the variation</strong> in <strong>usage</strong>.</p></li>
<li><p>While this indicates a moderate relationship, a significant portion of variation in <strong>CCU</strong> (%63.63) remains unexplained by <strong>PPI</strong> alone.</p></li>
</ul></li>
<li><p><strong>Adjusted R-squared:</strong> 0.35440</p>
<ul>
<li>This accounts for the number of predictors in the model and indicates a similar level of explanatory power.</li>
</ul></li>
</ul>
</section>
<section id="overall-model-significance" class="level3">
<h3 class="anchored" data-anchor-id="overall-model-significance">4. <strong>Overall Model Significance</strong></h3>
<ul>
<li><p><strong>F-statistic:</strong> 39.43 with a <strong>p-value</strong> of 2.615e-08</p>
<ul>
<li>This shows that the model as a whole is statistically significant, meaning that <strong>PPI</strong> is a significant predictor of <strong>CCU</strong>.</li>
</ul></li>
</ul>
</section>
<section id="residual-analysis" class="level3">
<h3 class="anchored" data-anchor-id="residual-analysis">5. <strong>Residual Analysis</strong></h3>
<ul>
<li><p>The residuals range from -74.31 to 102.6, with a residual standard error of 42.66.</p>
<ul>
<li>This indicates the variability of the predicted values around the observed values.</li>
</ul></li>
</ul>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion:</h3>
<p>The regression analysis suggests a <strong>moderate and statistically significant relationship</strong> between <strong>PPI</strong> and <strong>CCU.</strong> While the model demonstrates that PPI has a meaningful impact on usage, additional predictors or variables may be needed to better explain the variability in usage.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(table1, <span class="fu">aes</span>(<span class="at">x =</span> PPI, <span class="at">y =</span> usage)) <span class="sc">+</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span> </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Regression Analysis: PPI vs CCU"</span>,</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Producer Price Index (PPI)"</span>,</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Credit Card Usage (CCU)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Linear regression analysis indicates that these two indicators has a relation but we also try polynomial regression analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>modelpoly_ccu <span class="ot">&lt;-</span> <span class="fu">lm</span>(usage <span class="sc">~</span> <span class="fu">poly</span>(PPI, <span class="dv">2</span>), <span class="at">data =</span> table1)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelpoly_ccu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = usage ~ poly(PPI, 2), data = table1)

Residuals:
    Min      1Q  Median      3Q     Max 
-95.850 -26.289  -0.347  26.291  87.385 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     70.416      4.283  16.441  &lt; 2e-16 ***
poly(PPI, 2)1  267.905     36.090   7.423 2.44e-10 ***
poly(PPI, 2)2 -192.397     36.090  -5.331 1.20e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 36.09 on 68 degrees of freedom
Multiple R-squared:  0.5512,    Adjusted R-squared:  0.538 
F-statistic: 41.76 on 2 and 68 DF,  p-value: 1.475e-12</code></pre>
</div>
</div>
</section>
<section id="regression-equation-1" class="level3">
<h3 class="anchored" data-anchor-id="regression-equation-1">1. <strong>Regression Equation</strong></h3>
<p>The model includes a quadratic term:</p>
<p><strong>CCU=70.416 + ( 267.905 x poly(PPI,2) + ( -192.397 x poly(PPI,2) 2 )</strong></p>
<p><strong>2.Significance of Coefficients</strong></p>
<ul>
<li><p><strong>Intercept (70.416):</strong> Highly significant (p &lt; 2e -1 6)</p></li>
<li><p><strong>First-degree term (267.905):</strong> Highly significant (p = 2.44e-10)</p></li>
<li><p><strong>Second-degree term (-192.397):</strong> Highly significant (p = 1.20e - 06)</p></li>
</ul>
<p>Both polynomial terms are statistically significant, confirming the nonlinear relationship between <strong>CCU</strong> and <strong>PPI</strong>.</p>
</section>
<section id="model-fit-1" class="level3">
<h3 class="anchored" data-anchor-id="model-fit-1">3. <strong>Model Fit</strong></h3>
<ul>
<li><p><strong>Multiple R-squared:</strong> 0.5512</p>
<ul>
<li>The model explains <strong>55.12% of the variation</strong> in <strong>CCU</strong>, which is a substantial improvement over the linear model (%36.37)</li>
</ul></li>
<li><p><strong>Adjusted R-squared:</strong> 0.538</p>
<ul>
<li>Accounts for the number of predictors and suggests good explanatory power.</li>
</ul></li>
</ul>
</section>
<section id="overall-model-significance-1" class="level3">
<h3 class="anchored" data-anchor-id="overall-model-significance-1">4. <strong>Overall Model Significance</strong></h3>
<ul>
<li><p><strong>F-statistic:</strong> 41.76 , p = 1.475e-12</p>
<ul>
<li>The model is highly statistically significant overall.</li>
</ul></li>
</ul>
</section>
<section id="residual-analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="residual-analysis-1">5. <strong>Residual Analysis</strong></h3>
<ul>
<li><p><strong>Residual standard error:</strong> 36.09</p>
<ul>
<li>Indicates variability in predicted values around the observed data.</li>
</ul></li>
</ul>
</section>
<section id="conclusion-1" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-1">Conclusion:</h3>
<p>The polynomial regression model provides a better fit compared to the linear model, explaining more variance in <strong>CCU</strong>. The significant quadratic term confirms that the relationship between <strong>CCU</strong> and <strong>PPI</strong> is nonlinear. This model captures the complexity of the relationship more effectively.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(table1, <span class="fu">aes</span>(<span class="at">x =</span> PPI, <span class="at">y =</span> usage)) <span class="sc">+</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span> </span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">2</span>), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>)<span class="sc">+</span> </span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Polynomial Regression: PPI vs CCU"</span>,</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Producer Price Index (PPI)"</span>,</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Credit Card Usage (CCU)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>PPI and HOUSING PRICE INDEX</strong></p>
<p>Our highest correlation value was 0.88 and it was between PPI and Housing Price Index.So we assume we can find a stronger relation and better understanding with regresssion analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>model_housing <span class="ot">&lt;-</span> <span class="fu">lm</span>(Housing_Percentage_Change <span class="sc">~</span> PPI, <span class="at">data =</span> ppi_housing)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_housing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Housing_Percentage_Change ~ PPI, data = ppi_housing)

Residuals:
    Min      1Q  Median      3Q     Max 
-38.310 -20.341  -0.811  12.877  56.734 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.44605    5.11180   0.479    0.634    
PPI          1.19120    0.07747  15.376   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 26.23 on 63 degrees of freedom
Multiple R-squared:  0.7896,    Adjusted R-squared:  0.7863 
F-statistic: 236.4 on 1 and 63 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="regression-equation-2" class="level3">
<h3 class="anchored" data-anchor-id="regression-equation-2">1. <strong>Regression Equation</strong></h3>
<p>The estimated regression equation is:</p>
<p>PPI = 9.086 + (0.6629 X Housing Percentage Change)</p>
<ul>
<li><p><strong>Intercept (9.086):</strong></p>
<ul>
<li><p>Represents the predicted <strong>PPI</strong> when <strong>Housing Percentage Change</strong> is zero.</p></li>
<li><p>Statistically significant (( p=0.0153 &lt; 0.05).</p></li>
</ul></li>
<li><p><strong>Housing Percentage Change Coefficient (0.6629):</strong></p>
<ul>
<li><p>Indicates that for every 1% increase in housing percentage change, <strong>PPI</strong> is expected to increase by 0.6629 units on average.</p></li>
<li><p>Highly significant (p &lt; 2e - 16)</p></li>
</ul></li>
</ul>
</section>
<section id="model-fit-2" class="level3">
<h3 class="anchored" data-anchor-id="model-fit-2">2. <strong>Model Fit</strong></h3>
<ul>
<li><p><strong>Multiple R-squared:</strong> 0.7896</p>
<ul>
<li>The model explains <strong>78.96% of the variation</strong> in <strong>PPI</strong>, indicating a very strong relationship.</li>
</ul></li>
<li><p><strong>Adjusted R-squared:</strong> 0.7863</p>
<ul>
<li>Adjusted for the number of predictors; it also confirms a strong explanatory power.</li>
</ul></li>
</ul>
</section>
<section id="model-significance" class="level3">
<h3 class="anchored" data-anchor-id="model-significance">3. <strong>Model Significance</strong></h3>
<ul>
<li><p><strong>F-statistic:</strong> 236.4, p&lt; 2.2e - 16</p>
<ul>
<li>The overall model is highly statistically significant, confirming that <strong>Housing Percentage Change</strong> is a meaningful predictor of <strong>PPI</strong>.</li>
</ul></li>
</ul>
</section>
<section id="residual-analysis-2" class="level3">
<h3 class="anchored" data-anchor-id="residual-analysis-2">4. <strong>Residual Analysis</strong></h3>
<ul>
<li><p><strong>Residual Standard Error:</strong> 19.57</p>
<ul>
<li>Indicates the typical deviation of observed <strong>PPI</strong> values from the predicted values.</li>
</ul></li>
<li><p>Residuals are reasonably small, suggesting good model performance.</p></li>
</ul>
</section>
<section id="conclusion-2" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-2">Conclusion:</h3>
<p>The regression results show a strong, positive, and statistically significant relationship between <strong>Housing Percentage Change</strong> and <strong>PPI</strong>. The model explains nearly 79% of the variation in <strong>PPI</strong>, making it a robust predictor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ppi_housing, <span class="fu">aes</span>(<span class="at">x =</span> Housing_Percentage_Change, <span class="at">y =</span> PPI)) <span class="sc">+</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Regression for Housing PI and PPI"</span>,</span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Housing Price (Housing_Percentage_Change)"</span>,</span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"PPI (PPI)"</span>) <span class="sc">+</span></span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>PPI and Consumer Confidence Index</strong></p>
<p>Our previous analysis show that these two indicators has a coefficient value as 0.42.Although,this is a low value,it’s still our 4th highest correlation value.So,we will me a regression analysis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>model_confidence <span class="ot">&lt;-</span> <span class="fu">lm</span>(CCI <span class="sc">~</span> PPI, <span class="at">data =</span> data_yusuf1)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_confidence)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = CCI ~ PPI, data = data_yusuf1)

Residuals:
    Min      1Q  Median      3Q     Max 
-34.645  -6.981   2.473   8.071  21.732 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 149.44632    2.26154  66.082  &lt; 2e-16 ***
PPI           0.13652    0.03529   3.868 0.000246 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.02 on 69 degrees of freedom
Multiple R-squared:  0.1782,    Adjusted R-squared:  0.1663 
F-statistic: 14.96 on 1 and 69 DF,  p-value: 0.0002457</code></pre>
</div>
</div>
</section>
<section id="regression-equation-3" class="level3">
<h3 class="anchored" data-anchor-id="regression-equation-3">1. <strong>Regression Equation</strong></h3>
<p>The regression equation is:</p>
<p>CCI= 149.446+ (0.137 X PPI )</p>
<ul>
<li><p><strong>Intercept (149.446):</strong></p>
<ul>
<li><p>Represents the predicted <strong>CCI</strong> when <strong>PPI</strong> is zero.</p></li>
<li><p>Highly statistically significant (P &lt; 2E -16, indicating it holds meaningful information in this context.</p></li>
</ul></li>
<li><p><strong>PPI Coefficient (0.137):</strong></p>
<ul>
<li><p>Indicates that for every 1-unit increase in <strong>PPI</strong>, the <strong>CCI</strong> increases by 0.137 units on average.</p></li>
<li><p>Statistically significant (P = 0.000246&lt;0.05), showing that <strong>PPI</strong> has a meaningful impact on <strong>CCI</strong>.</p></li>
</ul></li>
</ul>
</section>
<section id="model-fit-3" class="level3">
<h3 class="anchored" data-anchor-id="model-fit-3">2. <strong>Model Fit</strong></h3>
<ul>
<li><p><strong>Multiple R-squared:</strong> 0.1782</p>
<ul>
<li>The model explains <strong>17.82% of the variation</strong> in <strong>CCI</strong>, which is relatively low. This suggests other factors not included in the model likely influence <strong>CCI</strong>.</li>
</ul></li>
<li><p><strong>Adjusted R-squared:</strong> 0.1663</p>
<ul>
<li>Adjusted for the number of predictors, it confirms the limited explanatory power of the model.</li>
</ul></li>
</ul>
</section>
<section id="model-significance-1" class="level3">
<h3 class="anchored" data-anchor-id="model-significance-1">3. <strong>Model Significance</strong></h3>
<ul>
<li><p><strong>F-statistic:</strong> 14.96,P = 0.0002457</p>
<ul>
<li>The model is statistically significant overall, indicating that <strong>PPI</strong> is a meaningful predictor of <strong>CCI</strong>.</li>
</ul></li>
</ul>
</section>
<section id="residual-analysis-3" class="level3">
<h3 class="anchored" data-anchor-id="residual-analysis-3">4. <strong>Residual Analysis</strong></h3>
<ul>
<li><p><strong>Residual Standard Error:</strong> 12.02</p>
<ul>
<li>Represents the typical deviation of the observed <strong>CCI</strong> values from the predicted values.</li>
</ul></li>
<li><p>Residuals show some spread, indicating potential unexplained variability in the model.</p></li>
</ul>
</section>
<section id="conclusion-3" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-3">Conclusion:</h3>
<p>While the regression identifies a statistically significant positive relationship between <strong>PPI</strong> and <strong>CCI</strong>, the low R<sup>2</sup> value suggests that <strong>PPI</strong> alone is not a strong predictor of <strong>CCI</strong>. Other variables likely influence <strong>CCI</strong>, and incorporating them could improve the model’s explanatory power.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_yusuf1, <span class="fu">aes</span>(<span class="at">x =</span> CCI, <span class="at">y =</span> PPI)) <span class="sc">+</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Regression for CCI and PPI"</span>,</span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span><span class="st">"CCI"</span>,</span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"PPI"</span>) <span class="sc">+</span></span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>MULTIPLE REGRESSION ANALYSIS</strong></p>
<p>We will implement a multıple regression analysis as our dependent variable is PPI and our independent variables is CCI,CCU and Housing PI.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>multi_reg_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(PPI <span class="sc">~</span> CCI <span class="sc">+</span> House <span class="sc">+</span> CCU, <span class="at">data =</span> ppi00)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(multi_reg_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PPI ~ CCI + House + CCU, data = ppi00)

Residuals:
    Min      1Q  Median      3Q     Max 
-33.286 -16.721   3.037  14.951  32.000 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -60.59278   28.57316  -2.121   0.0380 *  
CCI           0.47421    0.18971   2.500   0.0151 *  
House         0.66670    0.06205  10.745 1.06e-15 ***
CCU          -0.06419    0.06391  -1.004   0.3192    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.87 on 61 degrees of freedom
Multiple R-squared:  0.8105,    Adjusted R-squared:  0.8012 
F-statistic: 86.97 on 3 and 61 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="model-overview" class="level4">
<h4 class="anchored" data-anchor-id="model-overview">1. <strong>Model Overview</strong></h4>
<ul>
<li><p>The regression model predicts <strong>PPI</strong> (dependent variable) using <strong>CCI</strong>, <strong>House PI</strong>, and <strong>CCU</strong> (independent variables).</p></li>
<li><p>The overall model is statistically significant with a <strong>p-value &lt; 2.2e-16</strong>, indicating that at least one of the predictors significantly contributes to explaining the variability in PPI.</p></li>
</ul>
</section>
<section id="residuals" class="level4">
<h4 class="anchored" data-anchor-id="residuals">2. <strong>Residuals</strong></h4>
<ul>
<li>The residuals represent the differences between the observed and predicted values of <strong>PPI</strong>. They range from <strong>-33.286</strong> to <strong>32.000</strong>, with the median close to zero (<strong>3.037</strong>), indicating that the model predictions are reasonably centered around the actual values.</li>
</ul>
</section>
<section id="coefficients" class="level4">
<h4 class="anchored" data-anchor-id="coefficients">3. <strong>Coefficients</strong></h4>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Predictor</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t-value</th>
<th>p-value</th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>-60.59278</td>
<td>28.57316</td>
<td>-2.121</td>
<td>0.0380</td>
<td>*</td>
</tr>
<tr class="even">
<td>CCI</td>
<td>0.47421</td>
<td>0.18971</td>
<td>2.500</td>
<td>0.0151</td>
<td>*</td>
</tr>
<tr class="odd">
<td>House</td>
<td>0.66670</td>
<td>0.06205</td>
<td>10.745</td>
<td>1.06e-15</td>
<td>***</td>
</tr>
<tr class="even">
<td>CCU</td>
<td>-0.06419</td>
<td>0.06391</td>
<td>-1.004</td>
<td>0.3192</td>
<td></td>
</tr>
</tbody>
</table>
<ul>
<li><p><strong>Intercept (-60.593):</strong> When all predictors (<strong>CCI</strong>, <strong>House</strong>, and <strong>CCU</strong>) are zero, the expected value of <strong>PPI</strong> is <strong>-60.593</strong>. This may not have practical significance but serves as the model’s baseline.</p></li>
<li><p><strong>CCI (0.474):</strong> A one-unit increase in <strong>CCI</strong> is associated with an average increase of <strong>0.474</strong> units in <strong>PPI</strong>, holding other variables constant. This effect is statistically significant (<strong>p = 0.0151</strong>).</p></li>
<li><p><strong>House (0.667):</strong> A one-unit increase in <strong>House</strong> is associated with an average increase of <strong>0.667</strong> units in <strong>PPI</strong>, holding other variables constant. This predictor is highly significant (<strong>p = 1.06e-15</strong>).</p></li>
<li><p><strong>CCU (-0.064):</strong> A one-unit increase in <strong>CCU</strong> is associated with an average decrease of <strong>0.064</strong> units in <strong>PPI</strong>, but this effect is not statistically significant (<strong>p = 0.3192</strong>).</p></li>
</ul>
</section>
<section id="model-performance" class="level4">
<h4 class="anchored" data-anchor-id="model-performance">4. <strong>Model Performance</strong></h4>
<ul>
<li><p><strong>Residual Standard Error:</strong> 18.87, indicating the typical deviation of observed <strong>PPI</strong> values from the predicted values.</p></li>
<li><p><strong>Multiple R-squared (0.8105):</strong> The model explains approximately <strong>81.05%</strong> of the variability in <strong>PPI</strong>.</p></li>
<li><p><strong>Adjusted R-squared (0.8012):</strong> After adjusting for the number of predictors, the model still explains about <strong>80.12%</strong> of the variability in <strong>PPI</strong>, which is strong.</p></li>
</ul>
</section>
<section id="summary" class="level4">
<h4 class="anchored" data-anchor-id="summary">5. <strong>Summary</strong></h4>
<ul>
<li><p>The model is effective in explaining variations in <strong>PPI</strong>, particularly due to the significant contributions of <strong>CCI</strong> and <strong>House</strong>.</p></li>
<li><p>The predictor <strong>CCU</strong> does not significantly contribute to the model, and removing it might improve simplicity without sacrificing much explanatory power.</p></li>
<li><p>The high R<sup>2</sup> value and adjusted R<sup>2</sup> indicate a strong fit, but there may still be room for improvement by exploring additional predictors or refining the existing ones.</p></li>
</ul>


</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Hacettepe IE - EMU 430 - Fall 2024</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>